# 生产环境时开启页面的评论
[page.comment]
  enable = true
  # FixIt 0.2.16 | CHANGED Waline comment config (https://waline.js.org)
  [page.comment.waline]
    enable = true
    serverURL = "https://shuosc-comments.xyz/"
    pageview = false # FixIt 0.2.15 | NEW
    emoji = [
      "https://unpkg.com/@waline/emojis@1.1.0/bmoji",
      "https://unpkg.com/@waline/emojis@1.1.0/qq",
      "https://unpkg.com/@waline/emojis@1.1.0/alus",
      "//unpkg.com/@waline/emojis@1.1.0/weibo",
    ]
    # meta = ["nick", "mail", "link"]
    requiredMeta = ["mail"]
    # login = "enable"
    wordLimit = 1000
    # pageSize = 10
    # imageUploader = false # FixIt 0.2.15 | NEW
    highlighter = true # FixIt 0.2.15 | NEW
    comment = false # FixIt 0.2.15 | NEW
    texRenderer = true # FixIt 0.2.16 | NEW
    search = false # FixIt 0.2.16 | NEW
    # recaptchaV3Key = "" # FixIt 0.2.16 | NEW

# 生产环境时启用“不蒜子”计数器，以显示页面访问数的统计量
# "enable": 决定是否要显示站点的总访客数及总访问量
# "enablePost": 是否是否要显示每个页面各自的访客数及访问量
[ibruce]
  enable = true
  enablePost = true

# 生产环境时启用搜索功能
# FixIt 支持 lunr, algolia, fuse 这三种搜索引擎，其间的区别可参考：
# https://fixit.lruihao.cn/zh-cn/theme-documentation-basics/#52-%E6%90%9C%E7%B4%A2%E9%85%8D%E7%BD%AE
[search]
  enable = true
  # 搜索引擎的类型 ["lunr", "algolia", "fuse"]
  # 此处选用了 algolia , 优点为：性能相对较高且占用带宽低，缺点为：需要定期上传最新的 index.json 至 algolia 以保证搜索结果的时效性
  type = "algolia"
  # 文章内容最长索引长度
  contentLength = 200
  # 搜索框的占位提示语
  placeholder = ""
  #  最大结果数目
  maxResultLength = 30
  #  结果内容片段长度
  snippetLength = 200
  #  搜索结果中高亮部分的 HTML 标签
  highlightTag = "em"
  #  是否在搜索索引中使用基于 baseURL 的绝对路径
  absoluteURL = false
  [search.algolia]
    index = "shuosc_index_with_prefix"
    appID = "WDJUT0BGDL"
    searchKey = "56ca9e91d871934091cba0c69c69fd22"
  [search.fuse]
    #  https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = false
    ignoreFieldNorm = false


